#!/bin/sh

######
# Lyrics for Tuface Idibia 'For Instance'

echo 'See, for instance
Say I be the one wey dem give chance
Say I be the one wey dey make plans
For all man to benefit abi
To make we disagree to agree to create chance
But now I am not of importance
'Cause now I am looking from a distance
And that's why he give dem the chance to do us
And turn us to victim of circumstance'
#
##########
